### PR TITLE
Add selectable example contracts

### PR DESCRIPTION
**Pull request by sdankel**
Closes https://github.com/FuelLabs/sway-playground/issues/57

Testing requires running the server locally. 

Also added integration tests to make sure all examples compile. I had to combine the frontend and backend workflows in order to run the correct docker image for the integration test.

image

image

### CODE REVIEW

**Comment by JoshuaBatty** [comment]
Nice, I'm just wondering if we should have the UI widget be a drop down menu similar to what we are using to select the different networks?

**Comment by sdankel** [comment]
> Nice, I'm just wondering if we should have the UI widget be a drop down menu similar to what we are using to select the different networks?

Like a dropdown that says "examples" rather than an icon?

**Comment by JoshuaBatty** [comment]
Yeah, or potentially a side bar?

**Comment by sdankel** [comment]
I think a sidebar would look too crowded, but maybe there's a way to do I'm not thinking of. If you can share a mockup of what you have in mind it would be helpful!

**Comment by sdankel** [comment]
This is currently blocked by https://github.com/FuelLabs/fuelup/issues/598

**Comment by SilentCicero** [comment]
@sdankel agree with Josh here, it's unclear that button is actually a drop down, which is why it would be better to just have two drop downs here. Having the network selector is fine, but the network selector could be eventually moved to a higher level menu in the sway-playground app (it's usually top right corner or in settings) for example.

I'm going to approve and merge for now, we can make this adjustment in a future PR.

**Review by SilentCicero — APPROVED** [review]

**Pull request merged**
